# -*- coding: utf-8 -*-
"""Incentre_Triangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0Zkmy_CBj_ocso7mPN7jHbyFgF8EM5Z
"""

#Find Incentre of Triangle ABC
import numpy as np
  
A=np.array([6,-13]) 
B=np.array([6,18]) 
C=np.array([-2/3,2]) 

AB=np.linalg.norm(B-A)
BC=np.linalg.norm(C-B)
CA=np.linalg.norm(A-C)

in_centre = (A*BC+B*CA+C*AB)/(AB+BC+CA)

print("The incentre of triangle is", in_centre)